# Generated by Django 3.2.5 on 2021-08-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210818_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaria',
            name='data_atendimento',
            field=models.DateTimeField(),
        ),
    ]
