# Generated by Django 3.2.5 on 2021-08-25 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210819_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('transacao_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('diaria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.diaria')),
            ],
        ),
    ]
