# Generated by Django 3.2.5 on 2021-09-26 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnderecoDiarista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=60, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('bairro', models.CharField(max_length=30)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(max_length=10)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=2)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='endereco', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
