# Generated by Django 3.2.5 on 2021-10-20 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_enderecodiarista'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('nota', models.FloatField()),
                ('visibilidade', models.IntegerField()),
                ('avaliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliado', to=settings.AUTH_USER_MODEL)),
                ('avaliador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliador', to=settings.AUTH_USER_MODEL)),
                ('diaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_diaria', to='api.diaria')),
            ],
        ),
    ]
