# Generated by Django 3.2.5 on 2022-01-04 22:25

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20211123_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_documento',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.nome_arquivo_documento, validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_usuario',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.nome_arquivo_foto, validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
